services:
  db:
    container_name: ashi_db
    image: mysql:8.0.21
    ports:
      - "32001:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=ashi
      - MYSQL_USER=root
      - MYSQL_PASSWORD=my-secret-pw
    volumes:
      - ./ashi-db:/var/lib/mysql

  fastapi-app:
    build:
      context: .
      args:
        AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
        AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
        AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
    container_name: fastapi-app
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - db
    restart: always

  # nginx:
  #   build:
  #     context: ./nginx
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - fastapi-app
  #   restart: always

networks:
  app-network:
    driver: bridge
